components:
- xios-2.5-yac
- rnfmap-awicm-3.1
- oifs-43r3-awicm-3.2.1
- fesom-2.5
- oasis3mct-6.0-YAC
coupling_changes:
- sed -i '/COUPLENEMOECE = /s/.TRUE./.FALSE./g' oifs-43r3/src/ifs/module/yommcc.F90
- sed -i '/COUPLEFESOM2 = /s/.FALSE./.TRUE./g' oifs-43r3/src/ifs/module/yommcc.F90
- sed -i '/COUPLENEMOFOCI = /s/.TRUE./.FALSE./g' oifs-43r3/src/ifs/module/yommcc.F90

