comp:
        actual:
                files:
                    - "bin/fesom.x"
        check: {}
run:
        actual:
                errors:
                    - "MISSING FILES"
                files:
                    - "outdata/fesom/*.fesom.*.nc"
                    - "restart/fesom/fesom.*.oce.restart.nc*"
                    - "restart/fesom/fesom.*.ice.restart.nc*"
        check: {}
computers:
        - ollie
        - mistral
