components:
- xios-2.5
- rnfmap-awicm-3.1
- oifs-43r3-awicm-3.1.2
- fesom-2.0-awicm-3.1-recom3
- oasis3mct-4.0-awicm-3.1
coupling_changes:
- sed -i '/COUPLENEMOECE = /s/.TRUE./.FALSE./g' oifs-43r3/src/ifs/module/yommcc.F90
- sed -i '/COUPLEFESOM2 = /s/.FALSE./.TRUE./g' oifs-43r3/src/ifs/module/yommcc.F90
- sed -i '/COUPLENEMOFOCI = /s/.TRUE./.FALSE./g' oifs-43r3/src/ifs/module/yommcc.F90

