comp:
        actual:
                files:
                    - "bin/echam6"
                    - "bin/oceanx"
                    - "bin/xios.x"
        check: {}
        cp_instead_of_download:
                blogin:
                        foci-default: "/scratch/usr/hbkmandr/foci-default_2021-10-21.tar.gz"
                juwels:
                        foci-default: "/p/scratch/chhb19/mandresm/foci-default_2021-10-21.tar.gz"
run:
        actual:
                errors:
                    - "MISSING FILES"
                files:
                    - "outdata/echam/*_echam"
                    - "outdata/jsbach/*_jsbach"
                    - "outdata/nemo/mesh_mask_*"
                    - "restart/echam/restart_*nc"
                    - "restart/jsbach/restart_*nc"
                    - "restart/hdmodel/restart_*nc"
                    - "restart/nemo/*_restart_*"
                    - "restart/nemo/*_restart_ice_*"
                    - "restart/nemo/*_restart_trc_*"
                    - "restart/oasis3mct/flxatmos"
                    - "restart/oasis3mct/sstocean"
        check: {}
computer:
        - blogin
        - glogin
