model: debm
type: surface mass balance

available_versions:
- "1.0"
- "fortran"
- "update"
- "esm_tools"

version: "esm_tools"
choose_version:
    "1.0":
        branch: "1.0"
    "fortran":
        branch: "fortran"
    "update":
        branch: "update"
    "esm_tools":
        branch: "esm_tools"

clean_command: cd Fortran-v1.0; rm -rf build CMakeCache.txt
comp_command: cd Fortran-v1.0; mkdir -p build; cd build; cmake ..; make -j `nproc --all`
git-repository: https://github.com/ukrebska/dEBM
install_bins: Fortran-v1.0/bin/debm

metadata:
    Institute: AWI
    Description:
        dEBM is a surface melt scheme to couple ice and climate models in paleo applications.
    Publications:
        "Krebs-Kanzow, U., Gierz, P., and Lohmann, G., Brief communication: An Ice surface melt scheme including the diurnal cycle of solar radiation, The Cryosphere Discuss., accepted for publication <https://doi.org/10.5194/tc-2018-130>"
    License:
        MIT
