# MPIOM YAML CONFIGURATION FILE
#

metadata:
        Institute: MPI-Met
        Description:
                The ocean-sea ice component of the MPI-ESM. MPIOM is a primitive equation
                model (C-Grid, z-coordinates, free surface) with the hydrostatic and
                Boussinesq assumptions made.
        Authors: Till Maier-Reimer, Helmuth Haak, Johann Jungclaus
        Publications:
                - "Characteristics of the ocean simulations in the Max Planck Institute Ocean Model (MPIOM) the ocean component of the MPI-Earth system model <https://doi.org/10.1002/jame.20023>"
                - "The Max-Planck-Institute global ocean/sea ice model with orthogonal curvilinear coordinates <https://doi.org/10.1016/S1463-5003(02)00015-X>"
        License:
                Please make sure you have a licence to use MPIOM. In case you are unsure,
                please contact redmine...

resolution: GR15
