components:
- oifs-43r3-foci22
- nemo-ORCA05_LIM2_KCM_AOW_FS_OASISMCT4_SMAG
- oasis3mct-5.0-geomar 
- rnfmap-foci211
- xios-2.5_r1910
coupling_changes:
- sed -i '/COUPLENEMOECE = /s/.TRUE./.FALSE./g' oifs-43r3-foci22/src/ifs/module/yommcc.F90
- sed -i '/COUPLEFESOM2 = /s/.TRUE./.FALSE./g' oifs-43r3-foci22/src/ifs/module/yommcc.F90
- sed -i '/COUPLENEMOFOCI = /s/.FALSE./.TRUE./g' oifs-43r3-foci22/src/ifs/module/yommcc.F90
