components:
- echam-6.3.04p1
- fesom-2.0
- oasis3mct-2.8
coupling_changes:
- sed -i '/set(FESOM_COUPLED/s/OFF/ON/g' fesom-2.0/CMakeLists.txt
- sed -i '/ECHAM6_COUPLED/s/OFF/ON/g' echam-6.3.04p1/CMakeLists.txt
