model: oasis3mct
#model_dir: ${esm_master_dir}/oasis
cf_name_dir: ${model_dir}
time_step: 900 # changed by coupled setup anyway
norestart: F
use_lucia: False
mct_version: "5.0-geomar" # TODO: set mct_version = version (can't do at the moment as version is a string)
git-repository: https://gitlab.dkrz.de/modular_esm/oasis3-mct.git
contact: "miguel.andres-martinez(at)awi.de, paul.gierz(at)awi.de"

config_files:
        cf: cf

config_in_work:
        cf: "cf_name_table.txt"

config_sources:
        cf: "${cf_name_dir}/cf_name_table.txt"

version: '2.8'

available_versions:
- foci
- foci_autotools
- fociagrif
- ec-earth
- '2.8'
- '3.0'
- '4.0'
- '4.0-geomar'
- '4.0-oifsdeck'
- '4.0-awicm-frontiers'
- '4.0-awicm-3.0'
- '4.0-awicm-3.1'
- '5.0-smhi'
- '5.0-geomar'
choose_version:
  '2.8-paleodyn':
    branch: '2.8mct-awiesm-2.1'
    git-repository: https://gitlab.awi.de/paleodyn/Models/oasis3-mct.git

# kh 09.06.22
  '2.8-paleodyn-multi-group-support':
    branch: 'feat/multi-group-support'
    git-repository: https://gitlab.awi.de/paleodyn/Models/oasis3-mct.git
    
  '2.8':
    branch: 'v2.8'
  '3.0':
    branch: '3.0'
  '4.0':
    branch: '4.0'
  4.0-geomar:
    git-repository: https://git.geomar.de/foci/src/oasis3-mct4.git
    branch: '4.0'
    contact: "swahl(at)geomar.de"
  4.0-awicm-3.0:
    branch: awicm3-frontiers-freeze-candidate-1
  4.0-awicm-3.1:
    branch: awicm-3.1
  4.0-awicm-frontiers:
    branch: awicm-3-frontiers
  5.0-smhi:
    branch: main_dkrz
    git-repository: https://gitlab.dkrz.de/ec-earth/oasis3mct5-ece
  5.0-geomar:
    # this version is taken directly from the CERFACS gitlab
    # it compiles in the standard way, i.e. not with cmake
    branch: master
    git-repository: https://git.geomar.de/foci/src/oasis3-mct5.git 
    # compile with make -f TopMakefileOasis3
    # then copy all modules etc to a oasis/build/lib directory to match the older versions 
    comp_command: 'export ESM_OASIS_DIR=${model_dir} ; cd util/make_dir/ ; cp make.ESMTOOLS make.inc ; make -f TopMakefileOasis3 ; cd ../../ ; mv INSTALL_OASIS.ESMTOOLS/lib/libpsmile.MPI1.a INSTALL_OASIS.ESMTOOLS/lib/libpsmile.a ; mkdir -p build/lib/psmile/scrip ; mkdir -p build/lib/psmile/mct/mpeu ; cp INSTALL_OASIS.ESMTOOLS/build-static/lib/psmile.MPI1/*.mod build/lib/psmile/. ; cp INSTALL_OASIS.ESMTOOLS/build-static/lib/scrip/*mod build/lib/psmile/scrip/. ; cp INSTALL_OASIS.ESMTOOLS/build-static/lib/mct/*mod build/lib/psmile/mct/. ; cp INSTALL_OASIS.ESMTOOLS/lib/libmct.a build/lib/psmile/mct/. ; cp INSTALL_OASIS.ESMTOOLS/lib/libmpeu.a build/lib/psmile/mct/. ; cp INSTALL_OASIS.ESMTOOLS/lib/libpsmile.a build/lib/psmile/. ; cp INSTALL_OASIS.ESMTOOLS/lib/libscrip.a build/lib/psmile/scrip/. '
    install_libs:
    - INSTALL_OASIS.ESMTOOLS/lib/libpsmile.a
    - INSTALL_OASIS.ESMTOOLS/lib/libmct.a
    - INSTALL_OASIS.ESMTOOLS/lib/libmpeu.a
    - INSTALL_OASIS.ESMTOOLS/lib/libscrip.a
    # this is a quick fix for now
    clean_command: 'rm -rf INSTALL_OASIS.ESMTOOLS'
    # this is how we should do it but it does not work
    #clean_command: 'export ESM_OASIS_DIR=${model_dir} ; cd util/make_dir/ ; make -f TopMakefileOasis3 realclean ; cd ../../ ; rm -rf build lib/libpsmile.a lib/libscrip.a lib/libmct.a lib/libmpeu.a'
  ec-earth:
    branch: ec-earth-version
  foci:
    branch: oasis3mct2.8-foci
    git-repository: https://git.geomar.de/foci/src/oasis3mct.git
    contact: "swahl(at)geomar.de"
  foci_autotools:
    git-repository: https://git.geomar.de/foci/src/oasis3mct.git
    branch: master
    clean_command: make clean
    contact: "swahl(at)geomar.de"
    comp_command: ./configure --prefix=$(pwd)/../ CFLAGS="-O2 -DgFortran -std=gnu99" FCFLAGS="-I. -traceback -O3 -xHost -DTREAT_OVERLAY -Duse_netCDF -Duse_comm_MPI1" FFLAGS="-I. -traceback -O3 -xHost -DTREAT_OVERLAY -Duse_netCDF -Duse_comm_MPI1" ;
               make -j `nproc --all`; make install -j `nproc --all`;
    install_libs: ''
  fociagrif:
    branch: fociagrif
    git-repository: https://git.geomar.de/foci/src/oasis3-mct4.git
  EM21:
    branch: runoff
        
clean_command: 'rm -rf build CMakeCache.txt include lib/libpsmile.a lib/libscrip.a lib/libmct.a lib/libmpeu.a'
comp_command: 'mkdir -p build; cd build; cmake ..;   make -j 1; mkdir -p ../include/; cp lib/psmile/libpsmile.a lib/psmile/mct/libmct.a lib/psmile/mct/mpeu/libmpeu.a lib/psmile/scrip/libscrip.a ../lib; cp lib/psmile/mod_oasis*mod ../include '

destination: oasis
install_libs:
- build/lib/psmile/libpsmile.a
- build/lib/psmile/mct/libmct.a
- build/lib/psmile/mct/mpeu/libmpeu.a
- build/lib/psmile/scrip/libscrip.a


# for handling restarts
# this could be _19900101-19901231 for example
oasis_date_stamp: ""

#
# some default settings for remapping
# GAUSWGT with 9 neighbours and weight 2.0
# is fine when resolutions are similar
#
nb_of_neighbours_a2o: 9
weight_a2o: 2.0

log_files:
        nout: nout
        debug_r1: debug_r1
        debug_nr1: debug_nr1
        debug_r2: debug_r2
        debug_nr2: debug_nr2

log_sources:
        nout: nout.000000
        debug_r1: debug.root.01
        debug_nr1: debug_notroot.01
        debug_r2: debug.root.02
        debug_nr2: debug_notroot.02

log_in_work:
        nout: nout.000000
        debug_r1: debug.root.01
        debug_nr1: debug_notroot.01
        debug_r2: debug.root.02
        debug_nr2: debug_notroot.02

restart_out_files:
        areas: areas
        masks: masks
        grids: grids

restart_out_in_work:
        areas: areas.nc
        masks: masks.nc
        grids: grids.nc

restart_out_sources:
        areas: areas.nc
        masks: masks.nc
        grids: grids.nc

restart_in_files:
        areas: areas
        masks: masks
        grids: grids

restart_in_in_work:
        areas: areas.nc
        masks: masks.nc
        grids: grids.nc

restart_in_sources:
        areas: areas.nc
        masks: masks.nc
        grids: grids.nc

ignore_files:
        debug.root: debug.root
        debug.notroot: debug.notroot
        lucia: lucia
        nout: nout

ignore_in_work:
        debug.root: debug.root*
        debug.notroot: debug.notroot*
        lucia: lucia.*
        nout: nout.000000

ignore_sources:
        debug.root: debug.root*
        debug.notroot: debug.notroot*
        lucia: lucia.*
        nout: nout.000000


# transformations:
#
# time_transformation: instant / accumul / average / t_min / t_max
#
# preprocessing:
#       - checkin
#       - blasold:
#               xmult:
#               add_scalar: 0 / 1
#               scalar_to_add: (only if add_scalar == 1)
# remapping:
#       - mapping:
#               mapname: %filename with mapping matrix%
#               map_regrid_on: src / dst
#               mapstrategy:
#       - bilinear:
#               oasis_grid_type: LR / D / U, needs to be defined in model.yaml
#               search_bin: latitude / latlon
#               nb_of_search_bins: integer
#       - bicubic:
#               oasis_grid_type: LR / D / U, needs to be defined in model.yaml
#               search_bin: latitude / latlon
#               nb_of_search_bins: integer
#       - distwgt:
#               oasis_grid_type: LR / D / U, needs to be defined in model.yaml
#               search_bin: latitude / latlon
#               nb_of_search_bins: integer
#               nb_of_neighbours: integer
#       - gauswgt:
#               oasis_grid_type: LR / D / U, needs to be defined in model.yaml
#               search_bin: latitude / latlon
#               nb_of_search_bins: integer
#               nb_of_neighbours: integer
#               weigth: multiplicative weight, real
#      - conserv:
#               oasis_grid_type: LR / D / U, needs to be defined in model.yaml
#               search_bin: latitude / latlon
#               nb_of_search_bins: integer
#               normalization: fracarea / destarea / fracnnei
#               order: first / second
# postprocessing:
#       - checkout
#       - blasnew:
#               xmult:
#               add_scalar: 0 / 1
#               scalar_to_add: (only if add_scalar == 1)
#       - conserv:
#               method: GLOBAL / GLBPOS / BASBAL / BASPOS
#               algorithm:
#
#

further_reading:
    - oasis3mct/oasis3mct.env.yaml
