available_versions:
- 43r3-awi
- 43r3
- 40r1-foci
- 43r3-foci
- 40r1-agcm
- 40r1
choose_version:
  40r1:
    branch: foci_conserv
  40r1-agcm:
    compile_command: export OIFS_COMP=agcm; cd make; ../fcm/bin/fcm make -v -j8 -f
      oifs-agcm.cfg
  40r1-foci:
    branch: foci_conserv
    comp_command: cd make; ../fcm/bin/fcm make -v -j24 -f oifs.cfg
    destination: 40r1
  43r3:
    branch: oifs-deck
    comp_command: export OIFS_TOPLEVEL_DIR=${model_dir}; cd make; ../fcm/bin/fcm make
      -v -j8 -f oifs.cfg
    git-repository: https://gitlab.dkrz.de/ec-earth/oifs-43r3.git
  43r3-awi:
    branch: master
    comp_command: export OIFS_TOPLEVEL_DIR=${model_dir}; cd make; ../fcm/bin/fcm make
      -v -j8 -f oifs.cfg
    git-repository: https://gitlab.dkrz.de/ec-earth/oifs-43r3.git
  43r3-foci:
    branch: oifs-foci
    comp_command: export OIFS_TOPLEVEL_DIR=${model_dir}; cd make; ../fcm/bin/fcm make
      -v -j8 -f oifs.cfg
    git-repository: https://gitlab.dkrz.de/ec-earth/oifs-43r3.git
clean_command: rm -rf make/esm
comp_command: cd make; ../fcm/bin/fcm make -v -j8 -f oifs.cfg
git-repository: https://gitlab.dkrz.de/modular_esm/oifs-40r1.git
install_bins: make/esm/oifs/bin/master.exe
requires:
- oasis3-mct-4.0
