ollie:
        login_nodes:
                - 'ollie0'
                - 'ollie1'
        compute_nodes: 'prod-*'

mistral:
        login_nodes: 'mlogin*'
        compute_nodes: '^m[A-Za-z0-9]+\.hpc\.dkrz\.de$'
        post_nodes: 'mistralpp*'

juwels:
        #login_nodes: '^juwels[0-9][0-9]\.ib.juwels.fzj.de'
        #compute_nodes: '^jwc[0-9][0-9]*'
        login_nodes: '^jwlogin[0-9][0-9]\.juwels'
        compute_nodes: '^jwc[0-9][0-9]*'

blogin:
        login_nodes: 'blogin*'
        compute_nodes: '^b[A-Za-z0-9]+\.usr\.hlrn\.de$'
        post_nodes: 'blogin*'

glogin:
        login_nodes: 'glogin*'
        compute_nodes: '^g[A-Za-z0-9]+\.usr\.hlrn\.de$'
        post_nodes: 'glogin*'

aleph:
        login_nodes: 'elogin*'
        compute_nodes: 'mom*'
        post_nodes: 'elogin*'

nesh:
        login_nodes: 'nesh*'
        compute_nodes:
               - 'neshcl*'
               - 'nesh-bigmem*'
        post_nodes: 'neshcl*'

