choose_computer.name:
        ollie:
                compiletime_environment_changes:
                        add_export_vars:
                                - 'CFLAGS="-O2 -DgFortran -std=gnu99 -xHost"'
                                - 'FCFLAGS="-O3 -fpe0 -i4 -fp-model source -fast-transcendentals -no-prec-sqrt -xHost -heap-arrays -convert big_endian -fpp"'
                                - 'FFLAGS="$FCFLAGS"'
                                - 'ARFLAGS=crv'
                                - 'WLFLAG="-Wl"'
                                - 'OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"'
                                - 'OASIS3MCTROOT=${general.model_dir}'
                                - 'LIBS="-Wl,-rpath,$NETCDF_DIR/lib:$NETCDF_DIR/lib:$HDF5ROOT/lib:""/lib:${I_MPI_ROOT}/intel64/lib"'
        mistral:
                compiletime_environment_changes:
                        add_module_actions:
                                - "unload intel"
                                - "load intel/17.0.2"
                                - "unload intelmpi"
                                - "load intelmpi/2017.2.174"
                                - "unload gcc"
                                - "load gcc/4.8.2"
                                - "load cdo nco"
                                - "unload netcdf"
                                - "load netcdf_c/4.3.2-gcc48"
                        add_export_vars:
                                - 'CFLAGS="-O2 -DgFortran -std=gnu99"'
                                - 'FCFLAGS="-O3 -fp-model source -fast-transcendentals -no-prec-sqrt -xHost -heap-arrays -convert big_endian -fpp"'
                                - 'HDF5_ROOT="/sw/rhel6-x64/hdf5/hdf5-1.8.14-parallel-impi-intel14/"'
                                - 'NETCDFFROOT="/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.3-intel14"'
                                - 'NETCDFROOT="/sw/rhel6-x64/netcdf/netcdf_c-4.3.2-gcc48"'
                                - 'ARFLAGS=crv'
                                - 'WLFLAG="-Wl"'
                                - 'OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"'
                                - 'OASIS3MCTROOT=${general.model_dir}'
                                - 'LIBS="-Wl,-rpath,$NETCDFFROOT/lib:$NETCDFROOT/lib:$HDF5ROOT/lib:$SZIPROOT/lib:$MPIROOT/lib"'
                                - 'LD_LIBRARY_PATH="/sw/rhel6-x64/grib_api/grib_api-1.15.0-intel14/lib:$NETCDFFROOT/lib:$HDF5ROOT/lib:$NETCDFROOT/lib:$SZIPROOT/lib:$PROJ4_ROOT/lib:$LD_LIBRARY_PATH"'
