comp:
        actual:
                files:
                    - "bin/fesom.x"
                    - "bin/echam6"
        check: {}
run:
        actual:
                errors:
                    - "MISSING FILES"
                    - "Coupling var not found"
                files:
                    - "restart/echam/restart*.nc*"
                    - "restart/fesom/fesom.*.oce.restart.nc*"
                    - "restart/fesom/fesom.*.ice.restart.nc*"
                    - "outdata/echam/*"
                    # no daily output - "outdata/fesom/*.fesom.*.nc"
        check: {}
computers:
        - ollie
        - mistral
