# Setup up compile and runtime environment i.e. what needs
# to be changed w.r.t the default config/machines/<computer>.yaml

environment_changes:
    add_add_add_export_vars:
            DATA: "${general.work_dir}"
            LD_LIBRARY_PATH[(3)]: '$LD_LIBRARY_PATH:${thisrun_work_dir}/lib/oifs/'
            GRIB_SAMPLES_PATH: '${model_dir}/build/share/eccodes/ifs_samples/grib1_mlgrib2'
            OIFS_LOGFILE: '${model_dir}/build/oifs_test_log.txt'

    choose_computer.name:
        levante:
            compiler_mpi: gnu11_ompi4
            iolibraries: system_gnu_libs
            add_add_export_vars:
                OIFS_DATA_DIR: "/p/project/chhb19/streffing1/input/oifs-48r1/"
        juwels:
            compiler_mpi: gnu2023_ompi2023
            iolibraries: system_libs

