jobs:
  install_models:
    runs-on:
    - self-hosted
    - ollie
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      run: 'module purge

        module load git

        module load python3

        '
    - name: Generate virtualenv
      run: 'python -m venv env

        source env/bin/activate

        which python

        which pip

        echo $PATH'
    - name: Check versions and env
      run: 'git --version

        python --version

        pip --version

        env

        '
    - name: Install project
      run: pip install .
    - name: Check binaries
      run: 'export PATH=${HOME}/.local/bin:${PATH}

        which esm_master

        which esm_runscripts

        which esm_versions

        '
    - name: Check esm versions
      run: 'esm_versions check

        '
    - name: Install Model
      run: 'export PATH=${HOME}/.local/bin:${PATH}

        which esm_master

        esm_master --version

        rm -rf /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources

        mkdir -p /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources

        cd /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources/

        esm_master install-${{ matrix.model }}

        '
    - name: Cleanup Virtualenv
      run: rm -r env
    strategy:
      fail-fast: false
      matrix:
        model:
        - awicm-2.0-esm-interface
name: CI-Ollie-install-awicm-2.0-esm-interface
'on':
  pull_request:
    branches:
    - release
    - develop
    - '*prep-release*'
    paths:
    - configs/esm_master/setups/awicm.yaml
    - configs/esm_master/components/echam.yaml
    - configs/esm_master/components/fesom.yaml
    - configs/esm_master/couplings/fesom-2.0-esm-interface+echam-6.3.04p1-esm-interface.yaml
  push:
    branches:
    - release
    - develop
    - '*prep-release*'
    paths:
    - configs/esm_master/setups/awicm.yaml
    - configs/esm_master/components/echam.yaml
    - configs/esm_master/components/fesom.yaml
    - configs/esm_master/couplings/fesom-2.0-esm-interface+echam-6.3.04p1-esm-interface.yaml
