jobs:
  install_models:
    runs-on:
    - self-hosted
    - ollie
    steps:
    - uses: actions/checkout@v2
    - name: Compile Model
      run: 'module purge

        module load git

        module load python3/3.7.7_intel2020

        git --version

        which git

        python --version

        which python

        pwd

        ls -ratl

        rm -rf env

        python -m venv env

        source env/bin/activate

        which python

        which pip

        python --version

        pip --version

        pip install .

        which esm_master

        which esm_runscripts

        which esm_versions

        esm_versions check

        rm -rf /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources

        mkdir -p /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources

        cd /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources/

        esm_master install-${{ matrix.model }}

        '
    - name: Cleanup venv
      run: 'rm -rf env

        '
    strategy:
      fail-fast: false
      matrix:
        model:
        - awicmcr-2.0
name: CI-Ollie-install-awicmcr-2.0
'on':
  pull_request:
    branches:
    - release
    - develop
    - '*prep-release*'
    paths:
    - configs/esm_master/setups/awicmcr.yaml
    - configs/esm_master/components/fesom.yaml
    - configs/esm_master/components/echam.yaml
    - configs/esm_master/couplings/fesom-2.0+echam-6.3.05p2-concurrent_radiation.yaml
  push:
    branches:
    - release
    - develop
    - '*prep-release*'
    paths:
    - configs/esm_master/setups/awicmcr.yaml
    - configs/esm_master/components/fesom.yaml
    - configs/esm_master/components/echam.yaml
    - configs/esm_master/couplings/fesom-2.0+echam-6.3.05p2-concurrent_radiation.yaml
